apiVersion: v1
kind: Pod
metadata:
  labels:
    run: emptydir
    aula: day2
  name: emptydir
spec:
  containers:
  - image: nginx
    name: nginx-empty
    volumeMounts:
    - mountPath: /giropops
      name: volume-empty
    resources:
      limits:
        cpu: "1"
        memory: "128Mi"
      requests:
        cpu: "0.3"
        memory: "32Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: volume-empty
    emptyDir: 
      sizeLimit: 256Mi
