apiVersion: v1
kind: Pod
metadata:
  labels:
    run: triplea
    service: webserver
    aula: day2
  name: triplea
spec:
  containers:
  - image: nginx
    name: tripleb
    resources: {}
  - image: busybox
    name: triplec
    args: 
    - sleep
    - "600"
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
